### ISSUE TITLE
Can't get MSigDB

### ISSUE THREAD

**Issue by MhiroD** [montilab/hypeR#10]
Hi, hypeR developing team.
Thank you for your great package, hypeR.

I've used hypeR since this October, and there have been no problems for enrichment analysis. I tried to analyze another dataset today, I couldn't run "hyperdb_fetch()" and "hyperdb_info()".
```
>gsets <- hyperdb_fetch(type = "gsets", "KEGG_2019_Mouse")
Error in readRDS(temp) : unknown input format

```
```
>hyperdb_info()
Getting available gsets ... 
Error in gh("/repos/:owner/:repo/contents/:path", owner = "montilab",  : 
  GitHub API error (404): 404 Not Found
  Not Found
```
I got such error messages. 
Would you please give some tips for solving this problem?

Thank you.

R version: 3.6.1
Bioconductor version: 3.10
hypeR version: 1.2.0

**Comment by anfederico** [comment]
Please install the latest version of hypeR from Github. Also check out the latest docs to see updated functionality for retrieving genesets via hypeR: https://montilab.github.io/hypeR-docs/articles/docs/data.html.

The `hyperdb_fetch()` function actually pulled genesets originating from Enrichr, not Msigdb. Recently, rather than hosting these genesets, we added new functionality to pull genesets directly from Enrichr in the latest version of hypeR.

The following will get you the genesets you are looking for! The first is simply a list of genesets, the second is the same but wrapped in a `gsets` objects, which helps hypeR retain geneset versioning, and we recommend you use. Both can be passed to the `hyper()` function though.

```
genesets <- enrichr_download("KEGG_2019_Mouse")
gsets <- enrichr_gsets("KEGG_2019_Mouse")
```

**Comment by MhiroD** [comment]
Thank you for your reply!
I downloaded hypeR from Github and reloaded RStudio, then it gets to work! 

I always use hypeR for an enrichment analysis, so I was in a lot of trouble.
Thank you so much for your help. I'll keep using your package!

**Comment by anfederico** [comment]
Glad to hear it!
