### ISSUE TITLE
Error in hyp_hmap

### ISSUE THREAD

**Issue by tetomonti** [montilab/hypeR#41]
Here's an error when trying to generate reactable tables w/ hmaps included. I believe there is some limit case that is not checked for and gives error. You can find the rds here: [mhyp_obj.rds](https://www.dropbox.com/s/3jmjs2bf3875puw/mhyp_obj.rds?dl=0)

    library(hypeR)

    mhyp_obj <- readRDS("mhyp_obj.rds")`
    
    ## subsetting it to focus on the culprit entry
    mhyp_obj1 <- mhyp_obj$mhyp
    mhyp_obj1$data <- mhyp_obj1$data[10]
    
    rtbl <- hypeR::rctbl_build(mhyp_obj$mhyp,show_hmaps=TRUE)

Success!

    rtbl <- hypeR::rctbl_build(mhyp_obj$mhyp,show_hmaps=TRUE,hyp_hmap_args=list("fdr"=.5))

Error in min(x, na.rm = TRUE) : invalid 'type' (list) of argument

**Comment by anfederico** [comment]
Sorry this is a tough one to debug - so many nested functions!

The reason this is failing is because one of the `rgsets` object.

There is only one geneset `Tetrapyrroles` which meets the `FDR=0.5` threshold and this geneset is not listed in the `$nodes` property of the `rgsets` object. So the error comes from no nodes to plot.

Perhaps you can share how the `rgsets` object was constructed? That should solve the issue. Just need to make sure all of the `$genesets` are added as leaf-nodes to the `$nodes` property.

```R
rgset <- mhyp_obj1$data[[1]]$args$genesets

# Not all nodes must be genesets (internal nodes)
rgset$nodes$label %in% names(rgset$genesets)

# All genesets should be nodes (leaf nodes)
names(rgset$genesets) %in% rgset$nodes$label
```

**Comment by tetomonti** [comment]
Thank you Anthony, I found the error. 

When I was building the relational genesets, I was removing the self-loops and then defining the nodes based on the remaining edges, hence the problem. Which I now fixed. Plus, I see that now in your rgsets initialization code you have included a check for (and removal of) self-loops, so I could have just let it take care of it.

Sorry for the trouble.

—ste
